services:
  sub:
    build: .
    network_mode: host
    ipc: host
    tty: true
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./fastrtps-profile.xml:/tmp/fastrtps-profile.xml
      - ./volume:/root/workspace
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - DISPLAY=$DISPLAY
      - ROS_DOMAIN_ID=33
      - FASTRTPS_DEFAULT_PROFILES_FILE=/tmp/fastrtps-profile.xml
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities:
              - gpu
    command: ros2 run demo_nodes_cpp listener
